#!/bin/bash

set -euo pipefail

# Makes sure all the steps run on this same agent
sed "s/\$BUILDKITE_AGENT_META_DATA_NAME/$BUILDKITE_AGENT_META_DATA_NAME/" .ci/buildkite/pipeline.template.yml | sed "s/\$SWIFT_VERSION/`swiftenv local`/"
